### ISSUE TITLE
Auto size and auto repeat

### ISSUE THREAD

**Issue by Korsreven** [Korsreven/ion#139]
Add support for auto size and auto repeat in `graphics::scene::shapes::Sprite`. Auto size should automatically set the size of the sprite to the pixel size of the texture. Auto repeat should automatically repeat texture coordinates based on size of the sprite divided by the pixel size of the texture. All sprite sizes are in arbitrary units, so remember to convert between pixels and camera units.

**Comment by kimgea** [comment]
test
